# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/07-Databases

all:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn:      mysql:host=172.18.0.2;dbname=taller
      username: root
      password: secret
      attributes: 
        default_table_charset: utf8 
        default_table_collate: utf8_general_ci