<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2022/09/15 00:06:52
sfConfig::add(array(
  'app_aws_region' => 'us-east-1',
  'app_aws_version' => 'latest',
  'app_aws_key' => 'AKIASF5XSWKREP56QKEZ',
  'app_aws_secret' => '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',
));
