<?php

/**
 * ArchivosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ArchivosTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ArchivosTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Archivos');
    }
}