<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2022/09/14 23:58:10

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=172.18.0.2;dbname=taller',
  'username' => 'root',
  'password' => 'secret',
  'attributes' => 
  array (
    'default_table_charset' => 'utf8',
    'default_table_collate' => 'utf8_general_ci',
  ),
  'name' => 'doctrine',
)),);
