<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Archivos', 'doctrine');

/**
 * BaseArchivos
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property timestamp $fecha
 * @property string $nombre
 * @property string $archivo
 * 
 * @method integer   getId()      Returns the current record's "id" value
 * @method timestamp getFecha()   Returns the current record's "fecha" value
 * @method string    getNombre()  Returns the current record's "nombre" value
 * @method string    getArchivo() Returns the current record's "archivo" value
 * @method Archivos  setId()      Sets the current record's "id" value
 * @method Archivos  setFecha()   Sets the current record's "fecha" value
 * @method Archivos  setNombre()  Sets the current record's "nombre" value
 * @method Archivos  setArchivo() Sets the current record's "archivo" value
 * 
 * @package    taller
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseArchivos extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('archivos');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('fecha', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('nombre', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('archivo', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}